openapi: 3.0.0
info:
  title: User Registration API
  version: 1.0.0
paths:
  /users:
    post:
      summary: Create a new user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
      responses:
        '201':
          description: User created successfully
        '400':
          description: Bad request – validation failed
components:
  schemas:
    User:
      type: object
      required:
        - name
        - email
        - age
      properties:
        name:
          type: string
          example: John Doe
        email:
          type: string
          format: email
          example: john@example.com
        age:
          type: integer
          minimum: 18
          example: 25
        phone:
          type: string
          pattern: '^\\+?[0-9]{7,15}$'
          example: "+1234567890"
